services:
  db_hh:
    image: postgres:latest
    container_name: db_hh
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - hh_network

  test_db:
    image: postgres:latest
    container_name: test_db
    restart: always
    env_file:
      - .env.tests
    volumes:
      - test_postgres_data:/var/lib/postgresql
      - ./init_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    networks:
      - hh_network

  app_tg:
    build:
      dockerfile: Dockerfile
      context: project_tg
    container_name: app_tg
    restart: always
    ports:
      - "4444:4444"
    env_file:
      - ./project_tg/.env
    depends_on:
      - db_hh
    networks:
      - hh_network

#  pars_app:
#    build:
#      dockerfile: Dockerfile
#      context: project_parsing
#    container_name: parse_app
##    restart: always
#    env_file:
#      - .env
##    depends_on:
##      - db_hh
##      - redis
##      - app_tg
##      - fastapi_app
#    networks:
#      - hh_network
#
#  handler_api:
#    build:
#      dockerfile: Dockerfile
#      context: handler_api
#    container_name: handler_api
#    #    restart: always
##    env_file:
##      - project_parsing/.env
#    depends_on:
#      - db_hh
#      - app_tg
#      - fastapi_app
#    networks:
#      - hh_network

  fastapi_app:
    build:
      dockerfile: Dockerfile
      context: app
    container_name: fastapi_app
    restart: always
    environment:
      - PORT=8000
    env_file:
      - app/.env
    ports:
      - "8000:8000"
    depends_on:
      - db_hh
      - redis_hh
      - worker
      - clickhouse_log
    networks:
      - hh_network

  worker:
    build:
      dockerfile: Dockerfile
      context: app
    entrypoint: taskiq worker api.Dependencies.queue_data:broker
    env_file:
      - app/.env
    depends_on:
      - db_hh
      - redis_hh
      - clickhouse_log
    networks:
      - hh_network

  redis_hh:
    image: redis:latest
    container_name: redis_hh
    restart: always
    ports:
      - "6379:6379"
    networks:
      - hh_network

  clickhouse_log:
    image: clickhouse:latest
    container_name: clickhouse_log
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    ports:
      - "9000:9000"
      - "8123:8123"
    volumes:
      - ./init_db/click_house_init.sql:/docker-entrypoint-initdb.d/init-db.sql
      - clickhouse_data:/var/lib/clickhouse/
    networks:
      - hh_network

networks:
  hh_network:
    driver: bridge

volumes:
  postgres_data:
  clickhouse_data:
  test_postgres_data: