name: My First CI
on: push
#  push:
#    paths:
#      - "app/**"

jobs:
  our-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Run hello Action
        run: echo "Start Hello Action"

      - name: Check Dockerfile
        run: |
          echo "Проверяем на наличие Dockerfile"
          ls -la app/
          if [ -f "app/Dockerfile" ]; then
            echo "Dockerfile найден"
          else
            echo "Dockerfile не найден"
            exit 1
          fi

      - name: Check version python
        run: python --version

      - name: Docker image
        run: |
          echo "Сборка Dockerfile"
          docker build -t my-app:hh-app -f app/Dockerfile .

      - name: Docker run
        run: |
          docker run -d \
          -e PORT=8000 \
          -e APP_CONFIG__REDIS__URL=${{ secrets.APP_CONFIG__REDIS__URL }} \
          -e APP_CONFIG__REDIS__CHANNEL=${{ secrets.APP_CONFIG__REDIS__CHANNEL }} \
          -e APP_CONFIG__DB__URL=${{ secrets.APP_CONFIG__DB__URL }} \
          -e APP_CONFIG__PING_APP__URL=${{ secrets.APP_CONFIG__PING_APP__URL }} \
          --name app-container my-app:hh-app
          sleep 5
          if [ "$(docker inspect -f '{{.State.Running}}' app-container)" == "true" ]; then
            echo "Контейнер запущен"
            docker stop app-container
          else
            echo "Контейнер упал"
            docker logs app-container
            exit 1
          fi

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Testing app service
        working-directory: ./app
        run: |
          python -m pytest tests
