name: My First CI
on: push
#  push:
#    paths:
#      - "app/**"

jobs:
  our-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run hello Action
        run: echo "Start Hello Action"

      - name: Check Dockerfile
        run: |
          echo "Проверяем на наличие Dockerfile"
          ls -la app/
          if [ -f "app/Dockerfile" ]; then
            echo "Dockerfile найден"
          else
            echo "Dockerfile не найден"
            exit 1
          fi

      - name: Check version python
        run: python --version

      - name: Docker image
        run: |
          echo "Сборка Dockerfile"
          docker build -t my-app:hh-app -f app/Dockerfile app/

      - name: Docker run
        run: |
          docker run -d --name app-container my-app:hh-app
          sleep 5
          if [ "$(docker inspect -f '{{.State.Running}}' app-container)" == "true" ]; then
            echo "Контейнер запущен"
            docker stop app-container
          else
            echo "Контейнер упал"
            docker log app-container
            exit 1
          fi
